substitutions:
  device_name: akamatis-presence-sensor
  friendly_name: Akamatis Presence Sensor
  esp32_boot_pin: 9
  esp32_tx_pin: GPIO21
  esp32_rx_pin: GPIO20

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  comment: Akamatis HPS Firmware (LD2401/LD2410)
  name_add_mac_suffix: True
  project: 
    name: Akamatis.HumanPresenceSensor
    version: "1.1"

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

logger:
  level: INFO

api:

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: "Your Wi-Fi SSID"
  password: "Wi-Fi Password"
  power_save_mode: NONE
  reboot_timeout: 10min
  id: wifi_comp

  ap:
    ssid: "${friendly_name} Hotspot"
    password: ""

captive_portal:

uart:
  id: ld2410_uart
  tx_pin: ${esp32_tx_pin}
  rx_pin: ${esp32_rx_pin}
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

ld2410:
  uart_id: ld2410_uart
  id: ld2410_comp

select:
  - platform: ld2410
    distance_resolution:
      name: distance resolution
    baud_rate:
      name: baud rate
    light_function:
      name: light function
    out_pin_level:
      name: out pin level

binary_sensor:
  # Pressing the boot button will activate wifi hotspot within 10 sec
  # instead of waiting for the default 60 seconds.
  - platform: gpio
    pin:
      number: ${esp32_boot_pin}
      mode: INPUT_PULLUP
      inverted: true # Most boot buttons are active low
    name: "Boot Button"
    id: boot_button
    internal: True
    on_click:
      min_length: 3000ms
      max_length: 10000ms
      then:
        - logger.log: "Manually activating wifi hotspot: ..."
        - lambda: |-
            id(wifi_comp).set_ap_timeout(1);
            id(wifi_comp).disable();
            id(wifi_comp).clear_sta();
            id(wifi_comp).enable();
        - logger.log: "Manually activating wifi hotspot: done"

  - platform: ld2410
    has_target:
      name: Presence
    has_moving_target:
      name: Moving Target
    has_still_target:
      name: Still Target

text_sensor:
  - platform: ld2410
    version:
      name: "presenece sensor version"
    mac_address:
      name: "presenece sensor mac address"
 
switch:
  - platform: ld2410
    engineering_mode:
      name: "engineering mode"
    bluetooth:
      name: control Bluetooth

sensor:
  - platform: ld2410
    light:
      name: light
    moving_distance:
      name : Moving Distance
    still_distance:
      name: Still Distance
    moving_energy:
      name: Move Energy
    still_energy:
      name: Still Energy
    detection_distance:
      name: Detection Distance
    g0:
      move_energy:
        name: g0 move energy
      still_energy:
        name: g0 still energy
    g1:
      move_energy:
        name: g1 move energy
      still_energy:
        name: g1 still energy
    g2:
      move_energy:
        name: g2 move energy
      still_energy:
        name: g2 still energy
    g3:
      move_energy:
        name: g3 move energy
      still_energy:
        name: g3 still energy
    g4:
      move_energy:
        name: g4 move energy
      still_energy:
        name: g4 still energy
    g5:
      move_energy:
        name: g5 move energy
      still_energy:
        name: g5 still energy
    g6:
      move_energy:
        name: g6 move energy
      still_energy:
        name: g6 still energy
    g7:
      move_energy:
        name: g7 move energy
      still_energy:
        name: g7 still energy
    g8:
      move_energy:
        name: g8 move energy
      still_energy:
        name: g8 still energy

number:
  - platform: ld2410
    timeout:
      name: timeout
    light_threshold:
      name: light threshold
    max_move_distance_gate:
      name: max move distance gate
    max_still_distance_gate:
      name: max still distance gate
    g0:
      move_threshold:
        name: g0 move threshold
      still_threshold:
        name: g0 still threshold
    g1:
      move_threshold:
        name: g1 move threshold
      still_threshold:
        name: g1 still threshold
    g2:
      move_threshold:
        name: g2 move threshold
      still_threshold:
        name: g2 still threshold
    g3:
      move_threshold:
        name: g3 move threshold
      still_threshold:
        name: g3 still threshold
    g4:
      move_threshold:
        name: g4 move threshold
      still_threshold:
        name: g4 still threshold
    g5:
      move_threshold:
        name: g5 move threshold
      still_threshold:
        name: g5 still threshold
    g6:
      move_threshold:
        name: g6 move threshold
      still_threshold:
        name: g6 still threshold
    g7:
      move_threshold:
        name: g7 move threshold
      still_threshold:
        name: g7 still threshold
    g8:
      move_threshold:
        name: g8 move threshold
      still_threshold:
        name: g8 still threshold